# Generated by Django 4.1.3 on 2023-10-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="nameee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("author", models.CharField(max_length=30)),
                ("content", models.EmailField(max_length=255)),
            ],
            options={
                "db_table": "nameee",
            },
        ),
    ]
