# Generated by Django 4.1.3 on 2023-10-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nameee",
            name="title",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
