# Generated by Django 4.1.3 on 2023-10-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_alter_nameee_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nameee",
            name="author",
        ),
    ]
